// AUTO-GENERATED — do not edit. Run "pnpm run tokens:build" to regenerate.

export const tokens = {
  themes: {
    color: {
      onSubtle: {
        brand: {
          primary: 'var(--color-on-subtle-brand-primary)',
          secondary: 'var(--color-on-subtle-brand-secondary)',
          tertiary: 'var(--color-on-subtle-brand-tertiary)',
        },
        background: {
          default: 'var(--color-on-subtle-background-default)',
          sunken: 'var(--color-on-subtle-background-sunken)',
          subtle: 'var(--color-on-subtle-background-subtle)',
          inverse: 'var(--color-on-subtle-background-inverse)',
          overlay: 'var(--color-on-subtle-background-overlay)',
          brandPrimary: 'var(--color-on-subtle-background-brand-primary)',
        },
        text: {
          primary: 'var(--color-on-subtle-text-primary)',
          secondary: 'var(--color-on-subtle-text-secondary)',
          muted: 'var(--color-on-subtle-text-muted)',
          brand: 'var(--color-on-subtle-text-brand)',
        },
        icon: {
          default: 'var(--color-on-subtle-icon-default)',
        },
        border: {
          default: 'var(--color-on-subtle-border-default)',
        },
        ring: {
          default: 'var(--color-on-subtle-ring-default)',
        },
        link: {
          default: 'var(--color-on-subtle-link-default)',
          hover: 'var(--color-on-subtle-link-hover)',
        },
        control: {
          outline: {
            background: {
              default: 'var(--color-on-subtle-control-outline-background-default)',
              hover: 'var(--color-on-subtle-control-outline-background-hover)',
              active: 'var(--color-on-subtle-control-outline-background-active)',
              success: 'var(--color-on-subtle-control-outline-background-success)',
              error: 'var(--color-on-subtle-control-outline-background-error)',
              disabled: 'var(--color-on-subtle-control-outline-background-disabled)',
            },
            border: {
              default: 'var(--color-on-subtle-control-outline-border-default)',
              hover: 'var(--color-on-subtle-control-outline-border-hover)',
              active: 'var(--color-on-subtle-control-outline-border-active)',
              success: 'var(--color-on-subtle-control-outline-border-success)',
              error: 'var(--color-on-subtle-control-outline-border-error)',
              disabled: 'var(--color-on-subtle-control-outline-border-disabled)',
            },
            text: {
              default: 'var(--color-on-subtle-control-outline-text-default)',
              hover: 'var(--color-on-subtle-control-outline-text-hover)',
              active: 'var(--color-on-subtle-control-outline-text-active)',
              success: 'var(--color-on-subtle-control-outline-text-success)',
              error: 'var(--color-on-subtle-control-outline-text-error)',
              disabled: 'var(--color-on-subtle-control-outline-text-disabled)',
            },
            placeholder: {
              default: 'var(--color-on-subtle-control-outline-placeholder-default)',
              hover: 'var(--color-on-subtle-control-outline-placeholder-hover)',
              active: 'var(--color-on-subtle-control-outline-placeholder-active)',
              success: 'var(--color-on-subtle-control-outline-placeholder-success)',
              error: 'var(--color-on-subtle-control-outline-placeholder-error)',
              disabled: 'var(--color-on-subtle-control-outline-placeholder-disabled)',
            },
            icon: {
              default: 'var(--color-on-subtle-control-outline-icon-default)',
              hover: 'var(--color-on-subtle-control-outline-icon-hover)',
              active: 'var(--color-on-subtle-control-outline-icon-active)',
              success: 'var(--color-on-subtle-control-outline-icon-success)',
              error: 'var(--color-on-subtle-control-outline-icon-error)',
              disabled: 'var(--color-on-subtle-control-outline-icon-disabled)',
            },
            label: {
              default: 'var(--color-on-subtle-control-outline-label-default)',
              hover: 'var(--color-on-subtle-control-outline-label-hover)',
              active: 'var(--color-on-subtle-control-outline-label-active)',
              success: 'var(--color-on-subtle-control-outline-label-success)',
              error: 'var(--color-on-subtle-control-outline-label-error)',
              disabled: 'var(--color-on-subtle-control-outline-label-disabled)',
            },
            hint: {
              default: 'var(--color-on-subtle-control-outline-hint-default)',
              hover: 'var(--color-on-subtle-control-outline-hint-hover)',
              active: 'var(--color-on-subtle-control-outline-hint-active)',
              success: 'var(--color-on-subtle-control-outline-hint-success)',
              error: 'var(--color-on-subtle-control-outline-hint-error)',
              disabled: 'var(--color-on-subtle-control-outline-hint-disabled)',
            },
          },
          filled: {
            background: {
              default: 'var(--color-on-subtle-control-filled-background-default)',
              hover: 'var(--color-on-subtle-control-filled-background-hover)',
              active: 'var(--color-on-subtle-control-filled-background-active)',
              success: 'var(--color-on-subtle-control-filled-background-success)',
              error: 'var(--color-on-subtle-control-filled-background-error)',
              disabled: 'var(--color-on-subtle-control-filled-background-disabled)',
            },
            border: {
              default: 'var(--color-on-subtle-control-filled-border-default)',
              hover: 'var(--color-on-subtle-control-filled-border-hover)',
              active: 'var(--color-on-subtle-control-filled-border-active)',
              success: 'var(--color-on-subtle-control-filled-border-success)',
              error: 'var(--color-on-subtle-control-filled-border-error)',
              disabled: 'var(--color-on-subtle-control-filled-border-disabled)',
            },
            text: {
              default: 'var(--color-on-subtle-control-filled-text-default)',
              hover: 'var(--color-on-subtle-control-filled-text-hover)',
              active: 'var(--color-on-subtle-control-filled-text-active)',
              success: 'var(--color-on-subtle-control-filled-text-success)',
              error: 'var(--color-on-subtle-control-filled-text-error)',
              disabled: 'var(--color-on-subtle-control-filled-text-disabled)',
            },
            placeholder: {
              default: 'var(--color-on-subtle-control-filled-placeholder-default)',
              hover: 'var(--color-on-subtle-control-filled-placeholder-hover)',
              active: 'var(--color-on-subtle-control-filled-placeholder-active)',
              success: 'var(--color-on-subtle-control-filled-placeholder-success)',
              error: 'var(--color-on-subtle-control-filled-placeholder-error)',
              disabled: 'var(--color-on-subtle-control-filled-placeholder-disabled)',
            },
            icon: {
              default: 'var(--color-on-subtle-control-filled-icon-default)',
              hover: 'var(--color-on-subtle-control-filled-icon-hover)',
              active: 'var(--color-on-subtle-control-filled-icon-active)',
              success: 'var(--color-on-subtle-control-filled-icon-success)',
              error: 'var(--color-on-subtle-control-filled-icon-error)',
              disabled: 'var(--color-on-subtle-control-filled-icon-disabled)',
            },
            label: {
              default: 'var(--color-on-subtle-control-filled-label-default)',
              hover: 'var(--color-on-subtle-control-filled-label-hover)',
              active: 'var(--color-on-subtle-control-filled-label-active)',
              success: 'var(--color-on-subtle-control-filled-label-success)',
              error: 'var(--color-on-subtle-control-filled-label-error)',
              disabled: 'var(--color-on-subtle-control-filled-label-disabled)',
            },
            hint: {
              default: 'var(--color-on-subtle-control-filled-hint-default)',
              hover: 'var(--color-on-subtle-control-filled-hint-hover)',
              active: 'var(--color-on-subtle-control-filled-hint-active)',
              success: 'var(--color-on-subtle-control-filled-hint-success)',
              error: 'var(--color-on-subtle-control-filled-hint-error)',
              disabled: 'var(--color-on-subtle-control-filled-hint-disabled)',
            },
          },
        },
        feedback: {
          success: {
            base: 'var(--color-on-subtle-feedback-success-base)',
            subtle: 'var(--color-on-subtle-feedback-success-subtle)',
            onBase: 'var(--color-on-subtle-feedback-success-on-base)',
          },
          info: {
            base: 'var(--color-on-subtle-feedback-info-base)',
            subtle: 'var(--color-on-subtle-feedback-info-subtle)',
            onBase: 'var(--color-on-subtle-feedback-info-on-base)',
          },
          warning: {
            base: 'var(--color-on-subtle-feedback-warning-base)',
            subtle: 'var(--color-on-subtle-feedback-warning-subtle)',
            onBase: 'var(--color-on-subtle-feedback-warning-on-base)',
          },
          error: {
            base: 'var(--color-on-subtle-feedback-error-base)',
            subtle: 'var(--color-on-subtle-feedback-error-subtle)',
            onBase: 'var(--color-on-subtle-feedback-error-on-base)',
          },
        },
        action: {
          primary: {
            base: {
              default: 'var(--color-on-subtle-action-primary-base-default)',
              hover: 'var(--color-on-subtle-action-primary-base-hover)',
              focus: 'var(--color-on-subtle-action-primary-base-focus)',
              active: 'var(--color-on-subtle-action-primary-base-active)',
              disabled: 'var(--color-on-subtle-action-primary-base-disabled)',
            },
            onBase: {
              default: 'var(--color-on-subtle-action-primary-on-base-default)',
              hover: 'var(--color-on-subtle-action-primary-on-base-hover)',
              focus: 'var(--color-on-subtle-action-primary-on-base-focus)',
              active: 'var(--color-on-subtle-action-primary-on-base-active)',
              disabled: 'var(--color-on-subtle-action-primary-on-base-disabled)',
            },
          },
          secondary: {
            base: {
              default: 'var(--color-on-subtle-action-secondary-base-default)',
              hover: 'var(--color-on-subtle-action-secondary-base-hover)',
              focus: 'var(--color-on-subtle-action-secondary-base-focus)',
              active: 'var(--color-on-subtle-action-secondary-base-active)',
              disabled: 'var(--color-on-subtle-action-secondary-base-disabled)',
            },
            onBase: {
              default: 'var(--color-on-subtle-action-secondary-on-base-default)',
              hover: 'var(--color-on-subtle-action-secondary-on-base-hover)',
              focus: 'var(--color-on-subtle-action-secondary-on-base-focus)',
              active: 'var(--color-on-subtle-action-secondary-on-base-active)',
              disabled: 'var(--color-on-subtle-action-secondary-on-base-disabled)',
            },
          },
          tertiary: {
            base: {
              default: 'var(--color-on-subtle-action-tertiary-base-default)',
              hover: 'var(--color-on-subtle-action-tertiary-base-hover)',
              focus: 'var(--color-on-subtle-action-tertiary-base-focus)',
              active: 'var(--color-on-subtle-action-tertiary-base-active)',
              disabled: 'var(--color-on-subtle-action-tertiary-base-disabled)',
            },
            onBase: {
              default: 'var(--color-on-subtle-action-tertiary-on-base-default)',
              hover: 'var(--color-on-subtle-action-tertiary-on-base-hover)',
              focus: 'var(--color-on-subtle-action-tertiary-on-base-focus)',
              active: 'var(--color-on-subtle-action-tertiary-on-base-active)',
              disabled: 'var(--color-on-subtle-action-tertiary-on-base-disabled)',
            },
          },
          danger: {
            base: {
              default: 'var(--color-on-subtle-action-danger-base-default)',
              hover: 'var(--color-on-subtle-action-danger-base-hover)',
              focus: 'var(--color-on-subtle-action-danger-base-focus)',
              active: 'var(--color-on-subtle-action-danger-base-active)',
              disabled: 'var(--color-on-subtle-action-danger-base-disabled)',
            },
            onBase: {
              default: 'var(--color-on-subtle-action-danger-on-base-default)',
              hover: 'var(--color-on-subtle-action-danger-on-base-hover)',
              focus: 'var(--color-on-subtle-action-danger-on-base-focus)',
              active: 'var(--color-on-subtle-action-danger-on-base-active)',
              disabled: 'var(--color-on-subtle-action-danger-on-base-disabled)',
            },
          },
        },
        button: {
          primary: {
            background: {
              default: 'var(--color-on-subtle-button-primary-background-default)',
              hover: 'var(--color-on-subtle-button-primary-background-hover)',
              focus: 'var(--color-on-subtle-button-primary-background-focus)',
              active: 'var(--color-on-subtle-button-primary-background-active)',
              disabled: 'var(--color-on-subtle-button-primary-background-disabled)',
            },
            text: {
              default: 'var(--color-on-subtle-button-primary-text-default)',
              hover: 'var(--color-on-subtle-button-primary-text-hover)',
              focus: 'var(--color-on-subtle-button-primary-text-focus)',
              active: 'var(--color-on-subtle-button-primary-text-active)',
              disabled: 'var(--color-on-subtle-button-primary-text-disabled)',
            },
            border: {
              default: 'var(--color-on-subtle-button-primary-border-default)',
              hover: 'var(--color-on-subtle-button-primary-border-hover)',
              focus: 'var(--color-on-subtle-button-primary-border-focus)',
              active: 'var(--color-on-subtle-button-primary-border-active)',
              disabled: 'var(--color-on-subtle-button-primary-border-disabled)',
            },
          },
          secondary: {
            background: {
              default: 'var(--color-on-subtle-button-secondary-background-default)',
              hover: 'var(--color-on-subtle-button-secondary-background-hover)',
              focus: 'var(--color-on-subtle-button-secondary-background-focus)',
              active: 'var(--color-on-subtle-button-secondary-background-active)',
              disabled: 'var(--color-on-subtle-button-secondary-background-disabled)',
            },
            text: {
              default: 'var(--color-on-subtle-button-secondary-text-default)',
              hover: 'var(--color-on-subtle-button-secondary-text-hover)',
              focus: 'var(--color-on-subtle-button-secondary-text-focus)',
              active: 'var(--color-on-subtle-button-secondary-text-active)',
              disabled: 'var(--color-on-subtle-button-secondary-text-disabled)',
            },
            border: {
              default: 'var(--color-on-subtle-button-secondary-border-default)',
              hover: 'var(--color-on-subtle-button-secondary-border-hover)',
              focus: 'var(--color-on-subtle-button-secondary-border-focus)',
              active: 'var(--color-on-subtle-button-secondary-border-active)',
              disabled: 'var(--color-on-subtle-button-secondary-border-disabled)',
            },
          },
          outline: {
            background: {
              default: 'var(--color-on-subtle-button-outline-background-default)',
              hover: 'var(--color-on-subtle-button-outline-background-hover)',
              focus: 'var(--color-on-subtle-button-outline-background-focus)',
              active: 'var(--color-on-subtle-button-outline-background-active)',
              disabled: 'var(--color-on-subtle-button-outline-background-disabled)',
            },
            text: {
              default: 'var(--color-on-subtle-button-outline-text-default)',
              hover: 'var(--color-on-subtle-button-outline-text-hover)',
              focus: 'var(--color-on-subtle-button-outline-text-focus)',
              active: 'var(--color-on-subtle-button-outline-text-active)',
              disabled: 'var(--color-on-subtle-button-outline-text-disabled)',
            },
            border: {
              default: 'var(--color-on-subtle-button-outline-border-default)',
              hover: 'var(--color-on-subtle-button-outline-border-hover)',
              focus: 'var(--color-on-subtle-button-outline-border-focus)',
              active: 'var(--color-on-subtle-button-outline-border-active)',
              disabled: 'var(--color-on-subtle-button-outline-border-disabled)',
            },
          },
          ghost: {
            background: {
              default: 'var(--color-on-subtle-button-ghost-background-default)',
              hover: 'var(--color-on-subtle-button-ghost-background-hover)',
              focus: 'var(--color-on-subtle-button-ghost-background-focus)',
              active: 'var(--color-on-subtle-button-ghost-background-active)',
              disabled: 'var(--color-on-subtle-button-ghost-background-disabled)',
            },
            text: {
              default: 'var(--color-on-subtle-button-ghost-text-default)',
              hover: 'var(--color-on-subtle-button-ghost-text-hover)',
              focus: 'var(--color-on-subtle-button-ghost-text-focus)',
              active: 'var(--color-on-subtle-button-ghost-text-active)',
              disabled: 'var(--color-on-subtle-button-ghost-text-disabled)',
            },
            border: {
              default: 'var(--color-on-subtle-button-ghost-border-default)',
              hover: 'var(--color-on-subtle-button-ghost-border-hover)',
              focus: 'var(--color-on-subtle-button-ghost-border-focus)',
              active: 'var(--color-on-subtle-button-ghost-border-active)',
              disabled: 'var(--color-on-subtle-button-ghost-border-disabled)',
            },
          },
          danger: {
            background: {
              default: 'var(--color-on-subtle-button-danger-background-default)',
              hover: 'var(--color-on-subtle-button-danger-background-hover)',
              focus: 'var(--color-on-subtle-button-danger-background-focus)',
              active: 'var(--color-on-subtle-button-danger-background-active)',
              disabled: 'var(--color-on-subtle-button-danger-background-disabled)',
            },
            text: {
              default: 'var(--color-on-subtle-button-danger-text-default)',
              hover: 'var(--color-on-subtle-button-danger-text-hover)',
              focus: 'var(--color-on-subtle-button-danger-text-focus)',
              active: 'var(--color-on-subtle-button-danger-text-active)',
              disabled: 'var(--color-on-subtle-button-danger-text-disabled)',
            },
            border: {
              default: 'var(--color-on-subtle-button-danger-border-default)',
              hover: 'var(--color-on-subtle-button-danger-border-hover)',
              focus: 'var(--color-on-subtle-button-danger-border-focus)',
              active: 'var(--color-on-subtle-button-danger-border-active)',
              disabled: 'var(--color-on-subtle-button-danger-border-disabled)',
            },
          },
        },
      },
      onInverse: {
        brand: {
          primary: 'var(--color-on-inverse-brand-primary)',
          secondary: 'var(--color-on-inverse-brand-secondary)',
          tertiary: 'var(--color-on-inverse-brand-tertiary)',
        },
        background: {
          default: 'var(--color-on-inverse-background-default)',
          sunken: 'var(--color-on-inverse-background-sunken)',
          subtle: 'var(--color-on-inverse-background-subtle)',
          inverse: 'var(--color-on-inverse-background-inverse)',
          overlay: 'var(--color-on-inverse-background-overlay)',
          brandPrimary: 'var(--color-on-inverse-background-brand-primary)',
        },
        text: {
          primary: 'var(--color-on-inverse-text-primary)',
          secondary: 'var(--color-on-inverse-text-secondary)',
          muted: 'var(--color-on-inverse-text-muted)',
          brand: 'var(--color-on-inverse-text-brand)',
        },
        icon: {
          default: 'var(--color-on-inverse-icon-default)',
        },
        border: {
          default: 'var(--color-on-inverse-border-default)',
        },
        ring: {
          default: 'var(--color-on-inverse-ring-default)',
        },
        link: {
          default: 'var(--color-on-inverse-link-default)',
          hover: 'var(--color-on-inverse-link-hover)',
        },
        control: {
          outline: {
            background: {
              default: 'var(--color-on-inverse-control-outline-background-default)',
              hover: 'var(--color-on-inverse-control-outline-background-hover)',
              active: 'var(--color-on-inverse-control-outline-background-active)',
              success: 'var(--color-on-inverse-control-outline-background-success)',
              error: 'var(--color-on-inverse-control-outline-background-error)',
              disabled: 'var(--color-on-inverse-control-outline-background-disabled)',
            },
            border: {
              default: 'var(--color-on-inverse-control-outline-border-default)',
              hover: 'var(--color-on-inverse-control-outline-border-hover)',
              active: 'var(--color-on-inverse-control-outline-border-active)',
              success: 'var(--color-on-inverse-control-outline-border-success)',
              error: 'var(--color-on-inverse-control-outline-border-error)',
              disabled: 'var(--color-on-inverse-control-outline-border-disabled)',
            },
            text: {
              default: 'var(--color-on-inverse-control-outline-text-default)',
              hover: 'var(--color-on-inverse-control-outline-text-hover)',
              active: 'var(--color-on-inverse-control-outline-text-active)',
              success: 'var(--color-on-inverse-control-outline-text-success)',
              error: 'var(--color-on-inverse-control-outline-text-error)',
              disabled: 'var(--color-on-inverse-control-outline-text-disabled)',
            },
            placeholder: {
              default: 'var(--color-on-inverse-control-outline-placeholder-default)',
              hover: 'var(--color-on-inverse-control-outline-placeholder-hover)',
              active: 'var(--color-on-inverse-control-outline-placeholder-active)',
              success: 'var(--color-on-inverse-control-outline-placeholder-success)',
              error: 'var(--color-on-inverse-control-outline-placeholder-error)',
              disabled: 'var(--color-on-inverse-control-outline-placeholder-disabled)',
            },
            icon: {
              default: 'var(--color-on-inverse-control-outline-icon-default)',
              hover: 'var(--color-on-inverse-control-outline-icon-hover)',
              active: 'var(--color-on-inverse-control-outline-icon-active)',
              success: 'var(--color-on-inverse-control-outline-icon-success)',
              error: 'var(--color-on-inverse-control-outline-icon-error)',
              disabled: 'var(--color-on-inverse-control-outline-icon-disabled)',
            },
            label: {
              default: 'var(--color-on-inverse-control-outline-label-default)',
              hover: 'var(--color-on-inverse-control-outline-label-hover)',
              active: 'var(--color-on-inverse-control-outline-label-active)',
              success: 'var(--color-on-inverse-control-outline-label-success)',
              error: 'var(--color-on-inverse-control-outline-label-error)',
              disabled: 'var(--color-on-inverse-control-outline-label-disabled)',
            },
            hint: {
              default: 'var(--color-on-inverse-control-outline-hint-default)',
              hover: 'var(--color-on-inverse-control-outline-hint-hover)',
              active: 'var(--color-on-inverse-control-outline-hint-active)',
              success: 'var(--color-on-inverse-control-outline-hint-success)',
              error: 'var(--color-on-inverse-control-outline-hint-error)',
              disabled: 'var(--color-on-inverse-control-outline-hint-disabled)',
            },
          },
          filled: {
            background: {
              default: 'var(--color-on-inverse-control-filled-background-default)',
              hover: 'var(--color-on-inverse-control-filled-background-hover)',
              active: 'var(--color-on-inverse-control-filled-background-active)',
              success: 'var(--color-on-inverse-control-filled-background-success)',
              error: 'var(--color-on-inverse-control-filled-background-error)',
              disabled: 'var(--color-on-inverse-control-filled-background-disabled)',
            },
            border: {
              default: 'var(--color-on-inverse-control-filled-border-default)',
              hover: 'var(--color-on-inverse-control-filled-border-hover)',
              active: 'var(--color-on-inverse-control-filled-border-active)',
              success: 'var(--color-on-inverse-control-filled-border-success)',
              error: 'var(--color-on-inverse-control-filled-border-error)',
              disabled: 'var(--color-on-inverse-control-filled-border-disabled)',
            },
            text: {
              default: 'var(--color-on-inverse-control-filled-text-default)',
              hover: 'var(--color-on-inverse-control-filled-text-hover)',
              active: 'var(--color-on-inverse-control-filled-text-active)',
              success: 'var(--color-on-inverse-control-filled-text-success)',
              error: 'var(--color-on-inverse-control-filled-text-error)',
              disabled: 'var(--color-on-inverse-control-filled-text-disabled)',
            },
            placeholder: {
              default: 'var(--color-on-inverse-control-filled-placeholder-default)',
              hover: 'var(--color-on-inverse-control-filled-placeholder-hover)',
              active: 'var(--color-on-inverse-control-filled-placeholder-active)',
              success: 'var(--color-on-inverse-control-filled-placeholder-success)',
              error: 'var(--color-on-inverse-control-filled-placeholder-error)',
              disabled: 'var(--color-on-inverse-control-filled-placeholder-disabled)',
            },
            icon: {
              default: 'var(--color-on-inverse-control-filled-icon-default)',
              hover: 'var(--color-on-inverse-control-filled-icon-hover)',
              active: 'var(--color-on-inverse-control-filled-icon-active)',
              success: 'var(--color-on-inverse-control-filled-icon-success)',
              error: 'var(--color-on-inverse-control-filled-icon-error)',
              disabled: 'var(--color-on-inverse-control-filled-icon-disabled)',
            },
            label: {
              default: 'var(--color-on-inverse-control-filled-label-default)',
              hover: 'var(--color-on-inverse-control-filled-label-hover)',
              active: 'var(--color-on-inverse-control-filled-label-active)',
              success: 'var(--color-on-inverse-control-filled-label-success)',
              error: 'var(--color-on-inverse-control-filled-label-error)',
              disabled: 'var(--color-on-inverse-control-filled-label-disabled)',
            },
            hint: {
              default: 'var(--color-on-inverse-control-filled-hint-default)',
              hover: 'var(--color-on-inverse-control-filled-hint-hover)',
              active: 'var(--color-on-inverse-control-filled-hint-active)',
              success: 'var(--color-on-inverse-control-filled-hint-success)',
              error: 'var(--color-on-inverse-control-filled-hint-error)',
              disabled: 'var(--color-on-inverse-control-filled-hint-disabled)',
            },
          },
        },
        feedback: {
          success: {
            base: 'var(--color-on-inverse-feedback-success-base)',
            subtle: 'var(--color-on-inverse-feedback-success-subtle)',
            onBase: 'var(--color-on-inverse-feedback-success-on-base)',
          },
          info: {
            base: 'var(--color-on-inverse-feedback-info-base)',
            subtle: 'var(--color-on-inverse-feedback-info-subtle)',
            onBase: 'var(--color-on-inverse-feedback-info-on-base)',
          },
          warning: {
            base: 'var(--color-on-inverse-feedback-warning-base)',
            subtle: 'var(--color-on-inverse-feedback-warning-subtle)',
            onBase: 'var(--color-on-inverse-feedback-warning-on-base)',
          },
          error: {
            base: 'var(--color-on-inverse-feedback-error-base)',
            subtle: 'var(--color-on-inverse-feedback-error-subtle)',
            onBase: 'var(--color-on-inverse-feedback-error-on-base)',
          },
        },
        action: {
          primary: {
            base: {
              default: 'var(--color-on-inverse-action-primary-base-default)',
              hover: 'var(--color-on-inverse-action-primary-base-hover)',
              focus: 'var(--color-on-inverse-action-primary-base-focus)',
              active: 'var(--color-on-inverse-action-primary-base-active)',
              disabled: 'var(--color-on-inverse-action-primary-base-disabled)',
            },
            onBase: {
              default: 'var(--color-on-inverse-action-primary-on-base-default)',
              hover: 'var(--color-on-inverse-action-primary-on-base-hover)',
              focus: 'var(--color-on-inverse-action-primary-on-base-focus)',
              active: 'var(--color-on-inverse-action-primary-on-base-active)',
              disabled: 'var(--color-on-inverse-action-primary-on-base-disabled)',
            },
          },
          secondary: {
            base: {
              default: 'var(--color-on-inverse-action-secondary-base-default)',
              hover: 'var(--color-on-inverse-action-secondary-base-hover)',
              focus: 'var(--color-on-inverse-action-secondary-base-focus)',
              active: 'var(--color-on-inverse-action-secondary-base-active)',
              disabled: 'var(--color-on-inverse-action-secondary-base-disabled)',
            },
            onBase: {
              default: 'var(--color-on-inverse-action-secondary-on-base-default)',
              hover: 'var(--color-on-inverse-action-secondary-on-base-hover)',
              focus: 'var(--color-on-inverse-action-secondary-on-base-focus)',
              active: 'var(--color-on-inverse-action-secondary-on-base-active)',
              disabled: 'var(--color-on-inverse-action-secondary-on-base-disabled)',
            },
          },
          tertiary: {
            base: {
              default: 'var(--color-on-inverse-action-tertiary-base-default)',
              hover: 'var(--color-on-inverse-action-tertiary-base-hover)',
              focus: 'var(--color-on-inverse-action-tertiary-base-focus)',
              active: 'var(--color-on-inverse-action-tertiary-base-active)',
              disabled: 'var(--color-on-inverse-action-tertiary-base-disabled)',
            },
            onBase: {
              default: 'var(--color-on-inverse-action-tertiary-on-base-default)',
              hover: 'var(--color-on-inverse-action-tertiary-on-base-hover)',
              focus: 'var(--color-on-inverse-action-tertiary-on-base-focus)',
              active: 'var(--color-on-inverse-action-tertiary-on-base-active)',
              disabled: 'var(--color-on-inverse-action-tertiary-on-base-disabled)',
            },
          },
          danger: {
            base: {
              default: 'var(--color-on-inverse-action-danger-base-default)',
              hover: 'var(--color-on-inverse-action-danger-base-hover)',
              focus: 'var(--color-on-inverse-action-danger-base-focus)',
              active: 'var(--color-on-inverse-action-danger-base-active)',
              disabled: 'var(--color-on-inverse-action-danger-base-disabled)',
            },
            onBase: {
              default: 'var(--color-on-inverse-action-danger-on-base-default)',
              hover: 'var(--color-on-inverse-action-danger-on-base-hover)',
              focus: 'var(--color-on-inverse-action-danger-on-base-focus)',
              active: 'var(--color-on-inverse-action-danger-on-base-active)',
              disabled: 'var(--color-on-inverse-action-danger-on-base-disabled)',
            },
          },
        },
        button: {
          danger: {
            background: {
              active: 'var(--color-on-inverse-button-danger-background-active)',
              default: 'var(--color-on-inverse-button-danger-background-default)',
              disabled: 'var(--color-on-inverse-button-danger-background-disabled)',
              focus: 'var(--color-on-inverse-button-danger-background-focus)',
              hover: 'var(--color-on-inverse-button-danger-background-hover)',
            },
            border: {
              active: 'var(--color-on-inverse-button-danger-border-active)',
              default: 'var(--color-on-inverse-button-danger-border-default)',
              disabled: 'var(--color-on-inverse-button-danger-border-disabled)',
              focus: 'var(--color-on-inverse-button-danger-border-focus)',
              hover: 'var(--color-on-inverse-button-danger-border-hover)',
            },
            text: {
              active: 'var(--color-on-inverse-button-danger-text-active)',
              default: 'var(--color-on-inverse-button-danger-text-default)',
              disabled: 'var(--color-on-inverse-button-danger-text-disabled)',
              focus: 'var(--color-on-inverse-button-danger-text-focus)',
              hover: 'var(--color-on-inverse-button-danger-text-hover)',
            },
          },
          ghost: {
            text: {
              active: 'var(--color-on-inverse-button-ghost-text-active)',
              default: 'var(--color-on-inverse-button-ghost-text-default)',
              disabled: 'var(--color-on-inverse-button-ghost-text-disabled)',
              focus: 'var(--color-on-inverse-button-ghost-text-focus)',
              hover: 'var(--color-on-inverse-button-ghost-text-hover)',
            },
            background: {
              active: 'var(--color-on-inverse-button-ghost-background-active)',
              default: 'var(--color-on-inverse-button-ghost-background-default)',
              disabled: 'var(--color-on-inverse-button-ghost-background-disabled)',
              focus: 'var(--color-on-inverse-button-ghost-background-focus)',
              hover: 'var(--color-on-inverse-button-ghost-background-hover)',
            },
            border: {
              active: 'var(--color-on-inverse-button-ghost-border-active)',
              default: 'var(--color-on-inverse-button-ghost-border-default)',
              disabled: 'var(--color-on-inverse-button-ghost-border-disabled)',
              focus: 'var(--color-on-inverse-button-ghost-border-focus)',
              hover: 'var(--color-on-inverse-button-ghost-border-hover)',
            },
          },
          outline: {
            background: {
              active: 'var(--color-on-inverse-button-outline-background-active)',
              disabled: 'var(--color-on-inverse-button-outline-background-disabled)',
              focus: 'var(--color-on-inverse-button-outline-background-focus)',
              hover: 'var(--color-on-inverse-button-outline-background-hover)',
              default: 'var(--color-on-inverse-button-outline-background-default)',
            },
            border: {
              active: 'var(--color-on-inverse-button-outline-border-active)',
              default: 'var(--color-on-inverse-button-outline-border-default)',
              disabled: 'var(--color-on-inverse-button-outline-border-disabled)',
              focus: 'var(--color-on-inverse-button-outline-border-focus)',
              hover: 'var(--color-on-inverse-button-outline-border-hover)',
            },
            text: {
              active: 'var(--color-on-inverse-button-outline-text-active)',
              default: 'var(--color-on-inverse-button-outline-text-default)',
              disabled: 'var(--color-on-inverse-button-outline-text-disabled)',
              focus: 'var(--color-on-inverse-button-outline-text-focus)',
              hover: 'var(--color-on-inverse-button-outline-text-hover)',
            },
          },
          primary: {
            background: {
              active: 'var(--color-on-inverse-button-primary-background-active)',
              default: 'var(--color-on-inverse-button-primary-background-default)',
              disabled: 'var(--color-on-inverse-button-primary-background-disabled)',
              focus: 'var(--color-on-inverse-button-primary-background-focus)',
              hover: 'var(--color-on-inverse-button-primary-background-hover)',
            },
            border: {
              active: 'var(--color-on-inverse-button-primary-border-active)',
              default: 'var(--color-on-inverse-button-primary-border-default)',
              disabled: 'var(--color-on-inverse-button-primary-border-disabled)',
              focus: 'var(--color-on-inverse-button-primary-border-focus)',
              hover: 'var(--color-on-inverse-button-primary-border-hover)',
            },
            text: {
              active: 'var(--color-on-inverse-button-primary-text-active)',
              default: 'var(--color-on-inverse-button-primary-text-default)',
              disabled: 'var(--color-on-inverse-button-primary-text-disabled)',
              focus: 'var(--color-on-inverse-button-primary-text-focus)',
              hover: 'var(--color-on-inverse-button-primary-text-hover)',
            },
          },
          secondary: {
            background: {
              active: 'var(--color-on-inverse-button-secondary-background-active)',
              default: 'var(--color-on-inverse-button-secondary-background-default)',
              disabled: 'var(--color-on-inverse-button-secondary-background-disabled)',
              focus: 'var(--color-on-inverse-button-secondary-background-focus)',
              hover: 'var(--color-on-inverse-button-secondary-background-hover)',
            },
            border: {
              active: 'var(--color-on-inverse-button-secondary-border-active)',
              default: 'var(--color-on-inverse-button-secondary-border-default)',
              disabled: 'var(--color-on-inverse-button-secondary-border-disabled)',
              focus: 'var(--color-on-inverse-button-secondary-border-focus)',
              hover: 'var(--color-on-inverse-button-secondary-border-hover)',
            },
            text: {
              active: 'var(--color-on-inverse-button-secondary-text-active)',
              default: 'var(--color-on-inverse-button-secondary-text-default)',
              disabled: 'var(--color-on-inverse-button-secondary-text-disabled)',
              focus: 'var(--color-on-inverse-button-secondary-text-focus)',
              hover: 'var(--color-on-inverse-button-secondary-text-hover)',
            },
          },
        },
      },
      onBrandPrimary: {
        brand: {
          primary: 'var(--color-on-brand-primary-brand-primary)',
          secondary: 'var(--color-on-brand-primary-brand-secondary)',
          tertiary: 'var(--color-on-brand-primary-brand-tertiary)',
        },
        background: {
          default: 'var(--color-on-brand-primary-background-default)',
          sunken: 'var(--color-on-brand-primary-background-sunken)',
          subtle: 'var(--color-on-brand-primary-background-subtle)',
          inverse: 'var(--color-on-brand-primary-background-inverse)',
          overlay: 'var(--color-on-brand-primary-background-overlay)',
          brandPrimary: 'var(--color-on-brand-primary-background-brand-primary)',
        },
        text: {
          primary: 'var(--color-on-brand-primary-text-primary)',
          secondary: 'var(--color-on-brand-primary-text-secondary)',
          muted: 'var(--color-on-brand-primary-text-muted)',
          brand: 'var(--color-on-brand-primary-text-brand)',
        },
        icon: {
          default: 'var(--color-on-brand-primary-icon-default)',
        },
        border: {
          default: 'var(--color-on-brand-primary-border-default)',
        },
        ring: {
          default: 'var(--color-on-brand-primary-ring-default)',
        },
        link: {
          default: 'var(--color-on-brand-primary-link-default)',
          hover: 'var(--color-on-brand-primary-link-hover)',
        },
        control: {
          outline: {
            background: {
              default: 'var(--color-on-brand-primary-control-outline-background-default)',
              hover: 'var(--color-on-brand-primary-control-outline-background-hover)',
              active: 'var(--color-on-brand-primary-control-outline-background-active)',
              success: 'var(--color-on-brand-primary-control-outline-background-success)',
              error: 'var(--color-on-brand-primary-control-outline-background-error)',
              disabled: 'var(--color-on-brand-primary-control-outline-background-disabled)',
            },
            border: {
              default: 'var(--color-on-brand-primary-control-outline-border-default)',
              hover: 'var(--color-on-brand-primary-control-outline-border-hover)',
              active: 'var(--color-on-brand-primary-control-outline-border-active)',
              success: 'var(--color-on-brand-primary-control-outline-border-success)',
              error: 'var(--color-on-brand-primary-control-outline-border-error)',
              disabled: 'var(--color-on-brand-primary-control-outline-border-disabled)',
            },
            text: {
              default: 'var(--color-on-brand-primary-control-outline-text-default)',
              hover: 'var(--color-on-brand-primary-control-outline-text-hover)',
              active: 'var(--color-on-brand-primary-control-outline-text-active)',
              success: 'var(--color-on-brand-primary-control-outline-text-success)',
              error: 'var(--color-on-brand-primary-control-outline-text-error)',
              disabled: 'var(--color-on-brand-primary-control-outline-text-disabled)',
            },
            placeholder: {
              default: 'var(--color-on-brand-primary-control-outline-placeholder-default)',
              hover: 'var(--color-on-brand-primary-control-outline-placeholder-hover)',
              active: 'var(--color-on-brand-primary-control-outline-placeholder-active)',
              success: 'var(--color-on-brand-primary-control-outline-placeholder-success)',
              error: 'var(--color-on-brand-primary-control-outline-placeholder-error)',
              disabled: 'var(--color-on-brand-primary-control-outline-placeholder-disabled)',
            },
            icon: {
              default: 'var(--color-on-brand-primary-control-outline-icon-default)',
              hover: 'var(--color-on-brand-primary-control-outline-icon-hover)',
              active: 'var(--color-on-brand-primary-control-outline-icon-active)',
              success: 'var(--color-on-brand-primary-control-outline-icon-success)',
              error: 'var(--color-on-brand-primary-control-outline-icon-error)',
              disabled: 'var(--color-on-brand-primary-control-outline-icon-disabled)',
            },
            label: {
              default: 'var(--color-on-brand-primary-control-outline-label-default)',
              hover: 'var(--color-on-brand-primary-control-outline-label-hover)',
              active: 'var(--color-on-brand-primary-control-outline-label-active)',
              success: 'var(--color-on-brand-primary-control-outline-label-success)',
              error: 'var(--color-on-brand-primary-control-outline-label-error)',
              disabled: 'var(--color-on-brand-primary-control-outline-label-disabled)',
            },
            hint: {
              default: 'var(--color-on-brand-primary-control-outline-hint-default)',
              hover: 'var(--color-on-brand-primary-control-outline-hint-hover)',
              active: 'var(--color-on-brand-primary-control-outline-hint-active)',
              success: 'var(--color-on-brand-primary-control-outline-hint-success)',
              error: 'var(--color-on-brand-primary-control-outline-hint-error)',
              disabled: 'var(--color-on-brand-primary-control-outline-hint-disabled)',
            },
          },
          filled: {
            background: {
              default: 'var(--color-on-brand-primary-control-filled-background-default)',
              hover: 'var(--color-on-brand-primary-control-filled-background-hover)',
              active: 'var(--color-on-brand-primary-control-filled-background-active)',
              success: 'var(--color-on-brand-primary-control-filled-background-success)',
              error: 'var(--color-on-brand-primary-control-filled-background-error)',
              disabled: 'var(--color-on-brand-primary-control-filled-background-disabled)',
            },
            border: {
              default: 'var(--color-on-brand-primary-control-filled-border-default)',
              hover: 'var(--color-on-brand-primary-control-filled-border-hover)',
              active: 'var(--color-on-brand-primary-control-filled-border-active)',
              success: 'var(--color-on-brand-primary-control-filled-border-success)',
              error: 'var(--color-on-brand-primary-control-filled-border-error)',
              disabled: 'var(--color-on-brand-primary-control-filled-border-disabled)',
            },
            text: {
              default: 'var(--color-on-brand-primary-control-filled-text-default)',
              hover: 'var(--color-on-brand-primary-control-filled-text-hover)',
              active: 'var(--color-on-brand-primary-control-filled-text-active)',
              success: 'var(--color-on-brand-primary-control-filled-text-success)',
              error: 'var(--color-on-brand-primary-control-filled-text-error)',
              disabled: 'var(--color-on-brand-primary-control-filled-text-disabled)',
            },
            placeholder: {
              default: 'var(--color-on-brand-primary-control-filled-placeholder-default)',
              hover: 'var(--color-on-brand-primary-control-filled-placeholder-hover)',
              active: 'var(--color-on-brand-primary-control-filled-placeholder-active)',
              success: 'var(--color-on-brand-primary-control-filled-placeholder-success)',
              error: 'var(--color-on-brand-primary-control-filled-placeholder-error)',
              disabled: 'var(--color-on-brand-primary-control-filled-placeholder-disabled)',
            },
            icon: {
              default: 'var(--color-on-brand-primary-control-filled-icon-default)',
              hover: 'var(--color-on-brand-primary-control-filled-icon-hover)',
              active: 'var(--color-on-brand-primary-control-filled-icon-active)',
              success: 'var(--color-on-brand-primary-control-filled-icon-success)',
              error: 'var(--color-on-brand-primary-control-filled-icon-error)',
              disabled: 'var(--color-on-brand-primary-control-filled-icon-disabled)',
            },
            label: {
              default: 'var(--color-on-brand-primary-control-filled-label-default)',
              hover: 'var(--color-on-brand-primary-control-filled-label-hover)',
              active: 'var(--color-on-brand-primary-control-filled-label-active)',
              success: 'var(--color-on-brand-primary-control-filled-label-success)',
              error: 'var(--color-on-brand-primary-control-filled-label-error)',
              disabled: 'var(--color-on-brand-primary-control-filled-label-disabled)',
            },
            hint: {
              default: 'var(--color-on-brand-primary-control-filled-hint-default)',
              hover: 'var(--color-on-brand-primary-control-filled-hint-hover)',
              active: 'var(--color-on-brand-primary-control-filled-hint-active)',
              success: 'var(--color-on-brand-primary-control-filled-hint-success)',
              error: 'var(--color-on-brand-primary-control-filled-hint-error)',
              disabled: 'var(--color-on-brand-primary-control-filled-hint-disabled)',
            },
          },
        },
        feedback: {
          success: {
            base: 'var(--color-on-brand-primary-feedback-success-base)',
            subtle: 'var(--color-on-brand-primary-feedback-success-subtle)',
            onBase: 'var(--color-on-brand-primary-feedback-success-on-base)',
          },
          info: {
            base: 'var(--color-on-brand-primary-feedback-info-base)',
            subtle: 'var(--color-on-brand-primary-feedback-info-subtle)',
            onBase: 'var(--color-on-brand-primary-feedback-info-on-base)',
          },
          warning: {
            base: 'var(--color-on-brand-primary-feedback-warning-base)',
            subtle: 'var(--color-on-brand-primary-feedback-warning-subtle)',
            onBase: 'var(--color-on-brand-primary-feedback-warning-on-base)',
          },
          error: {
            base: 'var(--color-on-brand-primary-feedback-error-base)',
            subtle: 'var(--color-on-brand-primary-feedback-error-subtle)',
            onBase: 'var(--color-on-brand-primary-feedback-error-on-base)',
          },
        },
        action: {
          primary: {
            base: {
              default: 'var(--color-on-brand-primary-action-primary-base-default)',
              hover: 'var(--color-on-brand-primary-action-primary-base-hover)',
              focus: 'var(--color-on-brand-primary-action-primary-base-focus)',
              active: 'var(--color-on-brand-primary-action-primary-base-active)',
              disabled: 'var(--color-on-brand-primary-action-primary-base-disabled)',
            },
            onBase: {
              default: 'var(--color-on-brand-primary-action-primary-on-base-default)',
              hover: 'var(--color-on-brand-primary-action-primary-on-base-hover)',
              focus: 'var(--color-on-brand-primary-action-primary-on-base-focus)',
              active: 'var(--color-on-brand-primary-action-primary-on-base-active)',
              disabled: 'var(--color-on-brand-primary-action-primary-on-base-disabled)',
            },
          },
          secondary: {
            base: {
              default: 'var(--color-on-brand-primary-action-secondary-base-default)',
              hover: 'var(--color-on-brand-primary-action-secondary-base-hover)',
              focus: 'var(--color-on-brand-primary-action-secondary-base-focus)',
              active: 'var(--color-on-brand-primary-action-secondary-base-active)',
              disabled: 'var(--color-on-brand-primary-action-secondary-base-disabled)',
            },
            onBase: {
              default: 'var(--color-on-brand-primary-action-secondary-on-base-default)',
              hover: 'var(--color-on-brand-primary-action-secondary-on-base-hover)',
              focus: 'var(--color-on-brand-primary-action-secondary-on-base-focus)',
              active: 'var(--color-on-brand-primary-action-secondary-on-base-active)',
              disabled: 'var(--color-on-brand-primary-action-secondary-on-base-disabled)',
            },
          },
          tertiary: {
            base: {
              default: 'var(--color-on-brand-primary-action-tertiary-base-default)',
              hover: 'var(--color-on-brand-primary-action-tertiary-base-hover)',
              focus: 'var(--color-on-brand-primary-action-tertiary-base-focus)',
              active: 'var(--color-on-brand-primary-action-tertiary-base-active)',
              disabled: 'var(--color-on-brand-primary-action-tertiary-base-disabled)',
            },
            onBase: {
              default: 'var(--color-on-brand-primary-action-tertiary-on-base-default)',
              hover: 'var(--color-on-brand-primary-action-tertiary-on-base-hover)',
              focus: 'var(--color-on-brand-primary-action-tertiary-on-base-focus)',
              active: 'var(--color-on-brand-primary-action-tertiary-on-base-active)',
              disabled: 'var(--color-on-brand-primary-action-tertiary-on-base-disabled)',
            },
          },
          danger: {
            base: {
              default: 'var(--color-on-brand-primary-action-danger-base-default)',
              hover: 'var(--color-on-brand-primary-action-danger-base-hover)',
              focus: 'var(--color-on-brand-primary-action-danger-base-focus)',
              active: 'var(--color-on-brand-primary-action-danger-base-active)',
              disabled: 'var(--color-on-brand-primary-action-danger-base-disabled)',
            },
            onBase: {
              default: 'var(--color-on-brand-primary-action-danger-on-base-default)',
              hover: 'var(--color-on-brand-primary-action-danger-on-base-hover)',
              focus: 'var(--color-on-brand-primary-action-danger-on-base-focus)',
              active: 'var(--color-on-brand-primary-action-danger-on-base-active)',
              disabled: 'var(--color-on-brand-primary-action-danger-on-base-disabled)',
            },
          },
        },
        button: {
          danger: {
            background: {
              active: 'var(--color-on-brand-primary-button-danger-background-active)',
              default: 'var(--color-on-brand-primary-button-danger-background-default)',
              disabled: 'var(--color-on-brand-primary-button-danger-background-disabled)',
              focus: 'var(--color-on-brand-primary-button-danger-background-focus)',
              hover: 'var(--color-on-brand-primary-button-danger-background-hover)',
            },
            border: {
              active: 'var(--color-on-brand-primary-button-danger-border-active)',
              default: 'var(--color-on-brand-primary-button-danger-border-default)',
              disabled: 'var(--color-on-brand-primary-button-danger-border-disabled)',
              focus: 'var(--color-on-brand-primary-button-danger-border-focus)',
              hover: 'var(--color-on-brand-primary-button-danger-border-hover)',
            },
            text: {
              active: 'var(--color-on-brand-primary-button-danger-text-active)',
              default: 'var(--color-on-brand-primary-button-danger-text-default)',
              disabled: 'var(--color-on-brand-primary-button-danger-text-disabled)',
              focus: 'var(--color-on-brand-primary-button-danger-text-focus)',
              hover: 'var(--color-on-brand-primary-button-danger-text-hover)',
            },
          },
          ghost: {
            text: {
              active: 'var(--color-on-brand-primary-button-ghost-text-active)',
              default: 'var(--color-on-brand-primary-button-ghost-text-default)',
              disabled: 'var(--color-on-brand-primary-button-ghost-text-disabled)',
              focus: 'var(--color-on-brand-primary-button-ghost-text-focus)',
              hover: 'var(--color-on-brand-primary-button-ghost-text-hover)',
            },
            background: {
              active: 'var(--color-on-brand-primary-button-ghost-background-active)',
              default: 'var(--color-on-brand-primary-button-ghost-background-default)',
              disabled: 'var(--color-on-brand-primary-button-ghost-background-disabled)',
              focus: 'var(--color-on-brand-primary-button-ghost-background-focus)',
              hover: 'var(--color-on-brand-primary-button-ghost-background-hover)',
            },
            border: {
              active: 'var(--color-on-brand-primary-button-ghost-border-active)',
              default: 'var(--color-on-brand-primary-button-ghost-border-default)',
              disabled: 'var(--color-on-brand-primary-button-ghost-border-disabled)',
              focus: 'var(--color-on-brand-primary-button-ghost-border-focus)',
              hover: 'var(--color-on-brand-primary-button-ghost-border-hover)',
            },
          },
          outline: {
            background: {
              active: 'var(--color-on-brand-primary-button-outline-background-active)',
              disabled: 'var(--color-on-brand-primary-button-outline-background-disabled)',
              focus: 'var(--color-on-brand-primary-button-outline-background-focus)',
              hover: 'var(--color-on-brand-primary-button-outline-background-hover)',
              default: 'var(--color-on-brand-primary-button-outline-background-default)',
            },
            border: {
              active: 'var(--color-on-brand-primary-button-outline-border-active)',
              default: 'var(--color-on-brand-primary-button-outline-border-default)',
              disabled: 'var(--color-on-brand-primary-button-outline-border-disabled)',
              focus: 'var(--color-on-brand-primary-button-outline-border-focus)',
              hover: 'var(--color-on-brand-primary-button-outline-border-hover)',
            },
            text: {
              active: 'var(--color-on-brand-primary-button-outline-text-active)',
              default: 'var(--color-on-brand-primary-button-outline-text-default)',
              disabled: 'var(--color-on-brand-primary-button-outline-text-disabled)',
              focus: 'var(--color-on-brand-primary-button-outline-text-focus)',
              hover: 'var(--color-on-brand-primary-button-outline-text-hover)',
            },
          },
          primary: {
            background: {
              active: 'var(--color-on-brand-primary-button-primary-background-active)',
              default: 'var(--color-on-brand-primary-button-primary-background-default)',
              disabled: 'var(--color-on-brand-primary-button-primary-background-disabled)',
              focus: 'var(--color-on-brand-primary-button-primary-background-focus)',
              hover: 'var(--color-on-brand-primary-button-primary-background-hover)',
            },
            border: {
              active: 'var(--color-on-brand-primary-button-primary-border-active)',
              default: 'var(--color-on-brand-primary-button-primary-border-default)',
              disabled: 'var(--color-on-brand-primary-button-primary-border-disabled)',
              focus: 'var(--color-on-brand-primary-button-primary-border-focus)',
              hover: 'var(--color-on-brand-primary-button-primary-border-hover)',
            },
            text: {
              active: 'var(--color-on-brand-primary-button-primary-text-active)',
              default: 'var(--color-on-brand-primary-button-primary-text-default)',
              disabled: 'var(--color-on-brand-primary-button-primary-text-disabled)',
              focus: 'var(--color-on-brand-primary-button-primary-text-focus)',
              hover: 'var(--color-on-brand-primary-button-primary-text-hover)',
            },
          },
          secondary: {
            background: {
              active: 'var(--color-on-brand-primary-button-secondary-background-active)',
              default: 'var(--color-on-brand-primary-button-secondary-background-default)',
              disabled: 'var(--color-on-brand-primary-button-secondary-background-disabled)',
              focus: 'var(--color-on-brand-primary-button-secondary-background-focus)',
              hover: 'var(--color-on-brand-primary-button-secondary-background-hover)',
            },
            border: {
              active: 'var(--color-on-brand-primary-button-secondary-border-active)',
              default: 'var(--color-on-brand-primary-button-secondary-border-default)',
              disabled: 'var(--color-on-brand-primary-button-secondary-border-disabled)',
              focus: 'var(--color-on-brand-primary-button-secondary-border-focus)',
              hover: 'var(--color-on-brand-primary-button-secondary-border-hover)',
            },
            text: {
              active: 'var(--color-on-brand-primary-button-secondary-text-active)',
              default: 'var(--color-on-brand-primary-button-secondary-text-default)',
              disabled: 'var(--color-on-brand-primary-button-secondary-text-disabled)',
              focus: 'var(--color-on-brand-primary-button-secondary-text-focus)',
              hover: 'var(--color-on-brand-primary-button-secondary-text-hover)',
            },
          },
        },
      },
      selection: {
        background: 'var(--color-selection-background)',
        text: 'var(--color-selection-text)',
      },
    },
    typography: {
      heading: {
        fontFamily: 'var(--typography-heading-font-family)',
      },
      body: {
        fontFamily: 'var(--typography-body-font-family)',
      },
      caption: {
        fontFamily: 'var(--typography-caption-font-family)',
      },
    },
    radius: {
      sm: {
        mobile: 'var(--radius-sm-mobile)',
        desktop: 'var(--radius-sm-desktop)',
      },
      md: {
        mobile: 'var(--radius-md-mobile)',
        desktop: 'var(--radius-md-desktop)',
      },
      lg: {
        mobile: 'var(--radius-lg-mobile)',
        desktop: 'var(--radius-lg-desktop)',
      },
    },
    shadow: {
      color: {
        default: 'var(--shadow-color-default)',
        soft: 'var(--shadow-color-soft)',
        strong: 'var(--shadow-color-strong)',
      },
      elevation: {
        '1': 'var(--shadow-elevation-1)',
        '2': 'var(--shadow-elevation-2)',
        '3': 'var(--shadow-elevation-3)',
        '4': 'var(--shadow-elevation-4)',
      },
      interactive: {
        default: 'var(--shadow-interactive-default)',
        hover: 'var(--shadow-interactive-hover)',
        active: 'var(--shadow-interactive-active)',
      },
      inset: {
        default: 'var(--shadow-inset-default)',
        subtle: 'var(--shadow-inset-subtle)',
      },
    },
    button: {
      textTransform: {
        uppercase: 'var(--button-text-transform-uppercase)',
      },
    },
    ring: {
      style: 'var(--ring-style)',
      offset: 'var(--ring-offset)',
    },
    link: {
      textDecoration: {
        underline: 'var(--link-text-decoration-underline)',
      },
    },
  },
  surfaces: {
    color: {
      brand: {
        primary: 'var(--color-brand-primary)',
        secondary: 'var(--color-brand-secondary)',
        tertiary: 'var(--color-brand-tertiary)',
      },
      background: {
        default: 'var(--color-background-default)',
        sunken: 'var(--color-background-sunken)',
        subtle: 'var(--color-background-subtle)',
        inverse: 'var(--color-background-inverse)',
        overlay: 'var(--color-background-overlay)',
        brandPrimary: 'var(--color-background-brand-primary)',
      },
      text: {
        primary: 'var(--color-text-primary)',
        secondary: 'var(--color-text-secondary)',
        muted: 'var(--color-text-muted)',
        brand: 'var(--color-text-brand)',
      },
      icon: {
        default: 'var(--color-icon-default)',
      },
      border: {
        default: 'var(--color-border-default)',
      },
      ring: {
        default: 'var(--color-ring-default)',
      },
      link: {
        default: 'var(--color-link-default)',
        hover: 'var(--color-link-hover)',
      },
      control: {
        outline: {
          background: {
            default: 'var(--color-control-outline-background-default)',
            hover: 'var(--color-control-outline-background-hover)',
            active: 'var(--color-control-outline-background-active)',
            success: 'var(--color-control-outline-background-success)',
            error: 'var(--color-control-outline-background-error)',
            disabled: 'var(--color-control-outline-background-disabled)',
          },
          border: {
            default: 'var(--color-control-outline-border-default)',
            hover: 'var(--color-control-outline-border-hover)',
            active: 'var(--color-control-outline-border-active)',
            success: 'var(--color-control-outline-border-success)',
            error: 'var(--color-control-outline-border-error)',
            disabled: 'var(--color-control-outline-border-disabled)',
          },
          text: {
            default: 'var(--color-control-outline-text-default)',
            hover: 'var(--color-control-outline-text-hover)',
            active: 'var(--color-control-outline-text-active)',
            success: 'var(--color-control-outline-text-success)',
            error: 'var(--color-control-outline-text-error)',
            disabled: 'var(--color-control-outline-text-disabled)',
          },
          placeholder: {
            default: 'var(--color-control-outline-placeholder-default)',
            hover: 'var(--color-control-outline-placeholder-hover)',
            active: 'var(--color-control-outline-placeholder-active)',
            success: 'var(--color-control-outline-placeholder-success)',
            error: 'var(--color-control-outline-placeholder-error)',
            disabled: 'var(--color-control-outline-placeholder-disabled)',
          },
          icon: {
            default: 'var(--color-control-outline-icon-default)',
            hover: 'var(--color-control-outline-icon-hover)',
            active: 'var(--color-control-outline-icon-active)',
            success: 'var(--color-control-outline-icon-success)',
            error: 'var(--color-control-outline-icon-error)',
            disabled: 'var(--color-control-outline-icon-disabled)',
          },
          label: {
            default: 'var(--color-control-outline-label-default)',
            hover: 'var(--color-control-outline-label-hover)',
            active: 'var(--color-control-outline-label-active)',
            success: 'var(--color-control-outline-label-success)',
            error: 'var(--color-control-outline-label-error)',
            disabled: 'var(--color-control-outline-label-disabled)',
          },
          hint: {
            default: 'var(--color-control-outline-hint-default)',
            hover: 'var(--color-control-outline-hint-hover)',
            active: 'var(--color-control-outline-hint-active)',
            success: 'var(--color-control-outline-hint-success)',
            error: 'var(--color-control-outline-hint-error)',
            disabled: 'var(--color-control-outline-hint-disabled)',
          },
        },
        filled: {
          background: {
            default: 'var(--color-control-filled-background-default)',
            hover: 'var(--color-control-filled-background-hover)',
            active: 'var(--color-control-filled-background-active)',
            success: 'var(--color-control-filled-background-success)',
            error: 'var(--color-control-filled-background-error)',
            disabled: 'var(--color-control-filled-background-disabled)',
          },
          border: {
            default: 'var(--color-control-filled-border-default)',
            hover: 'var(--color-control-filled-border-hover)',
            active: 'var(--color-control-filled-border-active)',
            success: 'var(--color-control-filled-border-success)',
            error: 'var(--color-control-filled-border-error)',
            disabled: 'var(--color-control-filled-border-disabled)',
          },
          text: {
            default: 'var(--color-control-filled-text-default)',
            hover: 'var(--color-control-filled-text-hover)',
            active: 'var(--color-control-filled-text-active)',
            success: 'var(--color-control-filled-text-success)',
            error: 'var(--color-control-filled-text-error)',
            disabled: 'var(--color-control-filled-text-disabled)',
          },
          placeholder: {
            default: 'var(--color-control-filled-placeholder-default)',
            hover: 'var(--color-control-filled-placeholder-hover)',
            active: 'var(--color-control-filled-placeholder-active)',
            success: 'var(--color-control-filled-placeholder-success)',
            error: 'var(--color-control-filled-placeholder-error)',
            disabled: 'var(--color-control-filled-placeholder-disabled)',
          },
          icon: {
            default: 'var(--color-control-filled-icon-default)',
            hover: 'var(--color-control-filled-icon-hover)',
            active: 'var(--color-control-filled-icon-active)',
            success: 'var(--color-control-filled-icon-success)',
            error: 'var(--color-control-filled-icon-error)',
            disabled: 'var(--color-control-filled-icon-disabled)',
          },
          label: {
            default: 'var(--color-control-filled-label-default)',
            hover: 'var(--color-control-filled-label-hover)',
            active: 'var(--color-control-filled-label-active)',
            success: 'var(--color-control-filled-label-success)',
            error: 'var(--color-control-filled-label-error)',
            disabled: 'var(--color-control-filled-label-disabled)',
          },
          hint: {
            default: 'var(--color-control-filled-hint-default)',
            hover: 'var(--color-control-filled-hint-hover)',
            active: 'var(--color-control-filled-hint-active)',
            success: 'var(--color-control-filled-hint-success)',
            error: 'var(--color-control-filled-hint-error)',
            disabled: 'var(--color-control-filled-hint-disabled)',
          },
        },
      },
      feedback: {
        success: {
          base: 'var(--color-feedback-success-base)',
          subtle: 'var(--color-feedback-success-subtle)',
          onBase: 'var(--color-feedback-success-on-base)',
        },
        info: {
          base: 'var(--color-feedback-info-base)',
          subtle: 'var(--color-feedback-info-subtle)',
          onBase: 'var(--color-feedback-info-on-base)',
        },
        warning: {
          base: 'var(--color-feedback-warning-base)',
          subtle: 'var(--color-feedback-warning-subtle)',
          onBase: 'var(--color-feedback-warning-on-base)',
        },
        error: {
          base: 'var(--color-feedback-error-base)',
          subtle: 'var(--color-feedback-error-subtle)',
          onBase: 'var(--color-feedback-error-on-base)',
        },
      },
      action: {
        primary: {
          base: {
            default: 'var(--color-action-primary-base-default)',
            hover: 'var(--color-action-primary-base-hover)',
            focus: 'var(--color-action-primary-base-focus)',
            active: 'var(--color-action-primary-base-active)',
            disabled: 'var(--color-action-primary-base-disabled)',
          },
          onBase: {
            default: 'var(--color-action-primary-on-base-default)',
            hover: 'var(--color-action-primary-on-base-hover)',
            focus: 'var(--color-action-primary-on-base-focus)',
            active: 'var(--color-action-primary-on-base-active)',
            disabled: 'var(--color-action-primary-on-base-disabled)',
          },
        },
        secondary: {
          base: {
            default: 'var(--color-action-secondary-base-default)',
            hover: 'var(--color-action-secondary-base-hover)',
            focus: 'var(--color-action-secondary-base-focus)',
            active: 'var(--color-action-secondary-base-active)',
            disabled: 'var(--color-action-secondary-base-disabled)',
          },
          onBase: {
            default: 'var(--color-action-secondary-on-base-default)',
            hover: 'var(--color-action-secondary-on-base-hover)',
            focus: 'var(--color-action-secondary-on-base-focus)',
            active: 'var(--color-action-secondary-on-base-active)',
            disabled: 'var(--color-action-secondary-on-base-disabled)',
          },
        },
        tertiary: {
          base: {
            default: 'var(--color-action-tertiary-base-default)',
            hover: 'var(--color-action-tertiary-base-hover)',
            focus: 'var(--color-action-tertiary-base-focus)',
            active: 'var(--color-action-tertiary-base-active)',
            disabled: 'var(--color-action-tertiary-base-disabled)',
          },
          onBase: {
            default: 'var(--color-action-tertiary-on-base-default)',
            hover: 'var(--color-action-tertiary-on-base-hover)',
            focus: 'var(--color-action-tertiary-on-base-focus)',
            active: 'var(--color-action-tertiary-on-base-active)',
            disabled: 'var(--color-action-tertiary-on-base-disabled)',
          },
        },
        danger: {
          base: {
            default: 'var(--color-action-danger-base-default)',
            hover: 'var(--color-action-danger-base-hover)',
            focus: 'var(--color-action-danger-base-focus)',
            active: 'var(--color-action-danger-base-active)',
            disabled: 'var(--color-action-danger-base-disabled)',
          },
          onBase: {
            default: 'var(--color-action-danger-on-base-default)',
            hover: 'var(--color-action-danger-on-base-hover)',
            focus: 'var(--color-action-danger-on-base-focus)',
            active: 'var(--color-action-danger-on-base-active)',
            disabled: 'var(--color-action-danger-on-base-disabled)',
          },
        },
      },
      button: {
        danger: {
          background: {
            active: 'var(--color-button-danger-background-active)',
            default: 'var(--color-button-danger-background-default)',
            disabled: 'var(--color-button-danger-background-disabled)',
            focus: 'var(--color-button-danger-background-focus)',
            hover: 'var(--color-button-danger-background-hover)',
          },
          border: {
            active: 'var(--color-button-danger-border-active)',
            default: 'var(--color-button-danger-border-default)',
            disabled: 'var(--color-button-danger-border-disabled)',
            focus: 'var(--color-button-danger-border-focus)',
            hover: 'var(--color-button-danger-border-hover)',
          },
          text: {
            active: 'var(--color-button-danger-text-active)',
            default: 'var(--color-button-danger-text-default)',
            disabled: 'var(--color-button-danger-text-disabled)',
            focus: 'var(--color-button-danger-text-focus)',
            hover: 'var(--color-button-danger-text-hover)',
          },
        },
        ghost: {
          background: {
            active: 'var(--color-button-ghost-background-active)',
            default: 'var(--color-button-ghost-background-default)',
            disabled: 'var(--color-button-ghost-background-disabled)',
            focus: 'var(--color-button-ghost-background-focus)',
            hover: 'var(--color-button-ghost-background-hover)',
          },
          border: {
            active: 'var(--color-button-ghost-border-active)',
            default: 'var(--color-button-ghost-border-default)',
            disabled: 'var(--color-button-ghost-border-disabled)',
            focus: 'var(--color-button-ghost-border-focus)',
            hover: 'var(--color-button-ghost-border-hover)',
          },
          text: {
            active: 'var(--color-button-ghost-text-active)',
            default: 'var(--color-button-ghost-text-default)',
            disabled: 'var(--color-button-ghost-text-disabled)',
            focus: 'var(--color-button-ghost-text-focus)',
            hover: 'var(--color-button-ghost-text-hover)',
          },
        },
        outline: {
          background: {
            active: 'var(--color-button-outline-background-active)',
            default: 'var(--color-button-outline-background-default)',
            disabled: 'var(--color-button-outline-background-disabled)',
            focus: 'var(--color-button-outline-background-focus)',
            hover: 'var(--color-button-outline-background-hover)',
          },
          border: {
            active: 'var(--color-button-outline-border-active)',
            default: 'var(--color-button-outline-border-default)',
            disabled: 'var(--color-button-outline-border-disabled)',
            focus: 'var(--color-button-outline-border-focus)',
            hover: 'var(--color-button-outline-border-hover)',
          },
          text: {
            active: 'var(--color-button-outline-text-active)',
            default: 'var(--color-button-outline-text-default)',
            disabled: 'var(--color-button-outline-text-disabled)',
            focus: 'var(--color-button-outline-text-focus)',
            hover: 'var(--color-button-outline-text-hover)',
          },
        },
        primary: {
          background: {
            active: 'var(--color-button-primary-background-active)',
            default: 'var(--color-button-primary-background-default)',
            disabled: 'var(--color-button-primary-background-disabled)',
            focus: 'var(--color-button-primary-background-focus)',
            hover: 'var(--color-button-primary-background-hover)',
          },
          border: {
            active: 'var(--color-button-primary-border-active)',
            default: 'var(--color-button-primary-border-default)',
            disabled: 'var(--color-button-primary-border-disabled)',
            focus: 'var(--color-button-primary-border-focus)',
            hover: 'var(--color-button-primary-border-hover)',
          },
          text: {
            active: 'var(--color-button-primary-text-active)',
            default: 'var(--color-button-primary-text-default)',
            disabled: 'var(--color-button-primary-text-disabled)',
            focus: 'var(--color-button-primary-text-focus)',
            hover: 'var(--color-button-primary-text-hover)',
          },
        },
        secondary: {
          background: {
            active: 'var(--color-button-secondary-background-active)',
            default: 'var(--color-button-secondary-background-default)',
            disabled: 'var(--color-button-secondary-background-disabled)',
            focus: 'var(--color-button-secondary-background-focus)',
            hover: 'var(--color-button-secondary-background-hover)',
          },
          border: {
            active: 'var(--color-button-secondary-border-active)',
            default: 'var(--color-button-secondary-border-default)',
            disabled: 'var(--color-button-secondary-border-disabled)',
            focus: 'var(--color-button-secondary-border-focus)',
            hover: 'var(--color-button-secondary-border-hover)',
          },
          text: {
            active: 'var(--color-button-secondary-text-active)',
            default: 'var(--color-button-secondary-text-default)',
            disabled: 'var(--color-button-secondary-text-disabled)',
            focus: 'var(--color-button-secondary-text-focus)',
            hover: 'var(--color-button-secondary-text-hover)',
          },
        },
      },
    },
  },
  sizes: {
    typography: {
      heading: {
        display: {
          fontFamily: 'var(--typography-heading-display-font-family)',
          fontWeight: 'var(--typography-heading-display-font-weight)',
          fontWeightStrong: 'var(--typography-heading-display-font-weight-strong)',
          fontSize: 'var(--typography-heading-display-font-size)',
          lineHeight: 'var(--typography-heading-display-line-height)',
          letterSpacing: 'var(--typography-heading-display-letter-spacing)',
          large: {
            fontSize: 'var(--typography-heading-display-large-font-size)',
            lineHeight: 'var(--typography-heading-display-large-line-height)',
            letterSpacing: 'var(--typography-heading-display-large-letter-spacing)',
          },
        },
        title: {
          fontFamily: 'var(--typography-heading-title-font-family)',
          fontWeight: 'var(--typography-heading-title-font-weight)',
          fontWeightStrong: 'var(--typography-heading-title-font-weight-strong)',
          fontSize: 'var(--typography-heading-title-font-size)',
          lineHeight: 'var(--typography-heading-title-line-height)',
          letterSpacing: 'var(--typography-heading-title-letter-spacing)',
        },
        subtitle: {
          fontFamily: 'var(--typography-heading-subtitle-font-family)',
          fontWeight: 'var(--typography-heading-subtitle-font-weight)',
          fontWeightStrong: 'var(--typography-heading-subtitle-font-weight-strong)',
          fontSize: 'var(--typography-heading-subtitle-font-size)',
          lineHeight: 'var(--typography-heading-subtitle-line-height)',
          letterSpacing: 'var(--typography-heading-subtitle-letter-spacing)',
        },
        h1: {
          fontFamily: 'var(--typography-heading-h1-font-family)',
          fontWeight: 'var(--typography-heading-h1-font-weight)',
          fontSize: 'var(--typography-heading-h1-font-size)',
          lineHeight: 'var(--typography-heading-h1-line-height)',
          letterSpacing: 'var(--typography-heading-h1-letter-spacing)',
        },
        h2: {
          fontFamily: 'var(--typography-heading-h2-font-family)',
          fontWeight: 'var(--typography-heading-h2-font-weight)',
          fontSize: 'var(--typography-heading-h2-font-size)',
          lineHeight: 'var(--typography-heading-h2-line-height)',
          letterSpacing: 'var(--typography-heading-h2-letter-spacing)',
        },
        h3: {
          fontFamily: 'var(--typography-heading-h3-font-family)',
          fontWeight: 'var(--typography-heading-h3-font-weight)',
          fontSize: 'var(--typography-heading-h3-font-size)',
          lineHeight: 'var(--typography-heading-h3-line-height)',
          letterSpacing: 'var(--typography-heading-h3-letter-spacing)',
        },
        h4: {
          fontFamily: 'var(--typography-heading-h4-font-family)',
          fontWeight: 'var(--typography-heading-h4-font-weight)',
          fontSize: 'var(--typography-heading-h4-font-size)',
          lineHeight: 'var(--typography-heading-h4-line-height)',
          letterSpacing: 'var(--typography-heading-h4-letter-spacing)',
        },
        h5: {
          fontFamily: 'var(--typography-heading-h5-font-family)',
          fontWeight: 'var(--typography-heading-h5-font-weight)',
          fontSize: 'var(--typography-heading-h5-font-size)',
          lineHeight: 'var(--typography-heading-h5-line-height)',
          letterSpacing: 'var(--typography-heading-h5-letter-spacing)',
        },
        h6: {
          fontFamily: 'var(--typography-heading-h6-font-family)',
          fontWeight: 'var(--typography-heading-h6-font-weight)',
          fontSize: 'var(--typography-heading-h6-font-size)',
          lineHeight: 'var(--typography-heading-h6-line-height)',
          letterSpacing: 'var(--typography-heading-h6-letter-spacing)',
        },
      },
      body: {
        fontFamily: 'var(--typography-body-font-family)',
        fontWeight: 'var(--typography-body-font-weight)',
        fontWeightStrong: 'var(--typography-body-font-weight-strong)',
        fontSize: 'var(--typography-body-font-size)',
        lineHeight: 'var(--typography-body-line-height)',
        letterSpacing: 'var(--typography-body-letter-spacing)',
        small: {
          fontSize: 'var(--typography-body-small-font-size)',
          lineHeight: 'var(--typography-body-small-line-height)',
          letterSpacing: 'var(--typography-body-small-letter-spacing)',
        },
        large: {
          fontSize: 'var(--typography-body-large-font-size)',
          lineHeight: 'var(--typography-body-large-line-height)',
          letterSpacing: 'var(--typography-body-large-letter-spacing)',
        },
      },
      caption: {
        fontFamily: 'var(--typography-caption-font-family)',
        fontWeight: 'var(--typography-caption-font-weight)',
        fontSize: 'var(--typography-caption-font-size)',
        lineHeight: 'var(--typography-caption-line-height)',
        letterSpacing: 'var(--typography-caption-letter-spacing)',
      },
    },
    radius: {
      none: 'var(--radius-none)',
      sm: 'var(--radius-sm)',
      md: 'var(--radius-md)',
      lg: 'var(--radius-lg)',
      pill: 'var(--radius-pill)',
    },
    stroke: {
      border: 'var(--stroke-border)',
      ring: 'var(--stroke-ring)',
    },
    layout: {
      padding: {
        inline: {
          xs: 'var(--layout-padding-inline-xs)',
          sm: 'var(--layout-padding-inline-sm)',
          md: 'var(--layout-padding-inline-md)',
          lg: 'var(--layout-padding-inline-lg)',
          xl: 'var(--layout-padding-inline-xl)',
        },
        stack: {
          sm: 'var(--layout-padding-stack-sm)',
          md: 'var(--layout-padding-stack-md)',
          lg: 'var(--layout-padding-stack-lg)',
          xl: 'var(--layout-padding-stack-xl)',
        },
      },
      gap: {
        inline: {
          sm: 'var(--layout-gap-inline-sm)',
          md: 'var(--layout-gap-inline-md)',
          lg: 'var(--layout-gap-inline-lg)',
          lg2: 'var(--layout-gap-inline-lg-2)',
        },
        stack: {
          sm: 'var(--layout-gap-stack-sm)',
          md: 'var(--layout-gap-stack-md)',
          lg: 'var(--layout-gap-stack-lg)',
          xl: 'var(--layout-gap-stack-xl)',
        },
      },
      container: {
        maxWidth: 'var(--layout-container-max-width)',
        paddingInline: 'var(--layout-container-padding-inline)',
      },
    },
    icon: {
      sm: 'var(--icon-sm)',
      md: 'var(--icon-md)',
      lg: 'var(--icon-lg)',
    },
    control: {
      fontFamily: 'var(--control-font-family)',
      fontWeight: 'var(--control-font-weight)',
      fontSize: 'var(--control-font-size)',
      lineHeight: 'var(--control-line-height)',
      radius: 'var(--control-radius)',
      letterSpacing: 'var(--control-letter-spacing)',
      border: {
        width: 'var(--control-border-width)',
      },
      icon: {
        size: 'var(--control-icon-size)',
      },
      large: {
        fontSize: 'var(--control-large-font-size)',
        lineHeight: 'var(--control-large-line-height)',
        radius: 'var(--control-large-radius)',
        icon: {
          size: 'var(--control-large-icon-size)',
        },
        padding: {
          inline: 'var(--control-large-padding-inline)',
          inlineHasIcon: 'var(--control-large-padding-inline-has-icon)',
          stack: 'var(--control-large-padding-stack)',
        },
      },
      small: {
        fontSize: 'var(--control-small-font-size)',
        lineHeight: 'var(--control-small-line-height)',
        radius: 'var(--control-small-radius)',
        icon: {
          size: 'var(--control-small-icon-size)',
        },
        padding: {
          inline: 'var(--control-small-padding-inline)',
          inlineHasIcon: 'var(--control-small-padding-inline-has-icon)',
          stack: 'var(--control-small-padding-stack)',
        },
      },
      padding: {
        inline: 'var(--control-padding-inline)',
        inlineHasIcon: 'var(--control-padding-inline-has-icon)',
        stack: 'var(--control-padding-stack)',
      },
      underlined: {
        border: {
          width: {
            default: 'var(--control-underlined-border-width-default)',
            hover: 'var(--control-underlined-border-width-hover)',
            active: 'var(--control-underlined-border-width-active)',
            error: 'var(--control-underlined-border-width-error)',
            success: 'var(--control-underlined-border-width-success)',
            disabled: 'var(--control-underlined-border-width-disabled)',
          },
        },
      },
      label: {
        fontSize: 'var(--control-label-font-size)',
        lineHeight: 'var(--control-label-line-height)',
        fontWeight: 'var(--control-label-font-weight)',
        floating: {
          fontSize: 'var(--control-label-floating-font-size)',
          lineHeight: 'var(--control-label-floating-line-height)',
          fontWeight: 'var(--control-label-floating-font-weight)',
        },
      },
      hint: {
        fontSize: 'var(--control-hint-font-size)',
        lineHeight: 'var(--control-hint-line-height)',
        fontWeight: 'var(--control-hint-font-weight)',
      },
    },
    button: {
      fontFamily: 'var(--button-font-family)',
      fontWeight: 'var(--button-font-weight)',
      fontSize: 'var(--button-font-size)',
      lineHeight: 'var(--button-line-height)',
      radius: 'var(--button-radius)',
      letterSpacing: 'var(--button-letter-spacing)',
      border: {
        width: 'var(--button-border-width)',
      },
      icon: {
        size: 'var(--button-icon-size)',
      },
      textTransform: {
        uppercase: 'var(--button-text-transform-uppercase)',
      },
      padding: {
        inline: 'var(--button-padding-inline)',
        stack: 'var(--button-padding-stack)',
      },
      small: {
        fontSize: 'var(--button-small-font-size)',
        lineHeight: 'var(--button-small-line-height)',
        radius: 'var(--button-small-radius)',
        icon: {
          size: 'var(--button-small-icon-size)',
        },
        padding: {
          inline: 'var(--button-small-padding-inline)',
          stack: 'var(--button-small-padding-stack)',
        },
      },
      large: {
        fontSize: 'var(--button-large-font-size)',
        lineHeight: 'var(--button-large-line-height)',
        radius: 'var(--button-large-radius)',
        padding: {
          inline: 'var(--button-large-padding-inline)',
          stack: 'var(--button-large-padding-stack)',
        },
        icon: {
          size: 'var(--button-large-icon-size)',
        },
      },
    },
  },
} as const;

export type Tokens = typeof tokens;
type DeepValues<T> = T extends Record<string, unknown> ? DeepValues<T[keyof T]> : T;
export type TokenKey = DeepValues<Tokens>;
